export 
    INTEROPERABILITY_INDEX,
    INTEROPERABILITY_VERSION,
    NEW_SUBFILE_TYPE,
    IMAGE_WIDTH,
    IMAGE_LENGTH,
    BITS_PER_SAMPLE,
    COMPRESSION,
    PHOTOMETRIC_INTERPRETATION,
    FILL_ORDER,
    DOCUMENT_NAME,
    IMAGE_DESCRIPTION,
    MAKE,
    MODEL,
    STRIP_OFFSETS,
    ORIENTATION,
    SAMPLES_PER_PIXEL,
    ROWS_PER_STRIP,
    STRIP_BYTE_COUNTS,
    X_RESOLUTION,
    Y_RESOLUTION,
    PLANAR_CONFIGURATION,
    RESOLUTION_UNIT,
    TRANSFER_FUNCTION,
    SOFTWARE,
    DATE_TIME,
    ARTIST,
    WHITE_POINT,
    PRIMARY_CHROMATICITIES,
    SUB_IFDS,
    TRANSFER_RANGE,
    JPEG_PROC,
    JPEG_INTERCHANGE_FORMAT,
    JPEG_INTERCHANGE_FORMAT_LENGTH,
    YCBCR_COEFFICIENTS,
    YCBCR_SUB_SAMPLING,
    YCBCR_POSITIONING,
    REFERENCE_BLACK_WHITE,
    XML_PACKET,
    RELATED_IMAGE_FILE_FORMAT,
    RELATED_IMAGE_WIDTH,
    RELATED_IMAGE_LENGTH,
    CFA_REPEAT_PATTERN_DIM,
    CFA_PATTERN,
    BATTERY_LEVEL,
    COPYRIGHT,
    EXPOSURE_TIME,
    FNUMBER,
    IPTC_NAA,
    IMAGE_RESOURCES,
    EXIF_IFD_POINTER,
    INTER_COLOR_PROFILE,
    EXPOSURE_PROGRAM,
    SPECTRAL_SENSITIVITY,
    GPS_INFO_IFD_POINTER,
    ISO_SPEED_RATINGS,
    OECF,
    TIME_ZONE_OFFSET,
    EXIF_VERSION,
    DATE_TIME_ORIGINAL,
    DATE_TIME_DIGITIZED,
    COMPONENTS_CONFIGURATION,
    COMPRESSED_BITS_PER_PIXEL,
    SHUTTER_SPEED_VALUE,
    APERTURE_VALUE,
    BRIGHTNESS_VALUE,
    EXPOSURE_BIAS_VALUE,
    MAX_APERTURE_VALUE,
    SUBJECT_DISTANCE,
    METERING_MODE,
    LIGHT_SOURCE,
    FLASH,
    FOCAL_LENGTH,
    SUBJECT_AREA,
    TIFF_EP_STANDARD_ID,
    MAKER_NOTE,
    USER_COMMENT,
    SUB_SEC_TIME,
    SUB_SEC_TIME_ORIGINAL,
    SUB_SEC_TIME_DIGITIZED,
    XP_TITLE,
    XP_COMMENT,
    XP_AUTHOR,
    XP_KEYWORDS,
    XP_SUBJECT,
    FLASH_PIX_VERSION,
    COLOR_SPACE,
    PIXEL_X_DIMENSION,
    PIXEL_Y_DIMENSION,
    RELATED_SOUND_FILE,
    INTEROPERABILITY_IFD_POINTER,
    FLASH_ENERGY,
    SPATIAL_FREQUENCY_RESPONSE,
    FOCAL_PLANE_X_RESOLUTION,
    FOCAL_PLANE_Y_RESOLUTION,
    FOCAL_PLANE_RESOLUTION_UNIT,
    SUBJECT_LOCATION,
    EXPOSURE_INDEX,
    SENSING_METHOD,
    FILE_SOURCE,
    SCENE_TYPE,
    NEW_CFA_PATTERN,
    CUSTOM_RENDERED,
    EXPOSURE_MODE,
    WHITE_BALANCE,
    DIGITAL_ZOOM_RATIO,
    FOCAL_LENGTH_IN_35MM_FILM,
    SCENE_CAPTURE_TYPE,
    GAIN_CONTROL,
    CONTRAST,
    SATURATION,
    SHARPNESS,
    DEVICE_SETTING_DESCRIPTION,
    SUBJECT_DISTANCE_RANGE,
    IMAGE_UNIQUE_ID,
    GAMMA,
    PRINT_IMAGE_MATCHING,
    PADDING

const INTEROPERABILITY_INDEX = LibExif.EXIF_TAG_INTEROPERABILITY_INDEX
const INTEROPERABILITY_VERSION = LibExif.EXIF_TAG_INTEROPERABILITY_VERSION
const NEW_SUBFILE_TYPE = LibExif.EXIF_TAG_NEW_SUBFILE_TYPE
const IMAGE_WIDTH = LibExif.EXIF_TAG_IMAGE_WIDTH
const IMAGE_LENGTH = LibExif.EXIF_TAG_IMAGE_LENGTH
const BITS_PER_SAMPLE = LibExif.EXIF_TAG_BITS_PER_SAMPLE
const COMPRESSION = LibExif.EXIF_TAG_COMPRESSION
const PHOTOMETRIC_INTERPRETATION = LibExif.EXIF_TAG_PHOTOMETRIC_INTERPRETATION
const FILL_ORDER = LibExif.EXIF_TAG_FILL_ORDER
const DOCUMENT_NAME = LibExif.EXIF_TAG_DOCUMENT_NAME
const IMAGE_DESCRIPTION = LibExif.EXIF_TAG_IMAGE_DESCRIPTION
const MAKE = LibExif.EXIF_TAG_MAKE
const MODEL = LibExif.EXIF_TAG_MODEL
const STRIP_OFFSETS = LibExif.EXIF_TAG_STRIP_OFFSETS
const ORIENTATION = LibExif.EXIF_TAG_ORIENTATION
const SAMPLES_PER_PIXEL = LibExif.EXIF_TAG_SAMPLES_PER_PIXEL
const ROWS_PER_STRIP = LibExif.EXIF_TAG_ROWS_PER_STRIP
const STRIP_BYTE_COUNTS = LibExif.EXIF_TAG_STRIP_BYTE_COUNTS
const X_RESOLUTION = LibExif.EXIF_TAG_X_RESOLUTION
const Y_RESOLUTION = LibExif.EXIF_TAG_Y_RESOLUTION
const PLANAR_CONFIGURATION = LibExif.EXIF_TAG_PLANAR_CONFIGURATION
const RESOLUTION_UNIT = LibExif.EXIF_TAG_RESOLUTION_UNIT
const TRANSFER_FUNCTION = LibExif.EXIF_TAG_TRANSFER_FUNCTION
const SOFTWARE = LibExif.EXIF_TAG_SOFTWARE
const DATE_TIME = LibExif.EXIF_TAG_DATE_TIME
const ARTIST = LibExif.EXIF_TAG_ARTIST
const WHITE_POINT = LibExif.EXIF_TAG_WHITE_POINT
const PRIMARY_CHROMATICITIES = LibExif.EXIF_TAG_PRIMARY_CHROMATICITIES
const SUB_IFDS = LibExif.EXIF_TAG_SUB_IFDS
const TRANSFER_RANGE = LibExif.EXIF_TAG_TRANSFER_RANGE
const JPEG_PROC = LibExif.EXIF_TAG_JPEG_PROC
const JPEG_INTERCHANGE_FORMAT = LibExif.EXIF_TAG_JPEG_INTERCHANGE_FORMAT
const JPEG_INTERCHANGE_FORMAT_LENGTH = LibExif.EXIF_TAG_JPEG_INTERCHANGE_FORMAT_LENGTH
const YCBCR_COEFFICIENTS = LibExif.EXIF_TAG_YCBCR_COEFFICIENTS
const YCBCR_SUB_SAMPLING = LibExif.EXIF_TAG_YCBCR_SUB_SAMPLING
const YCBCR_POSITIONING = LibExif.EXIF_TAG_YCBCR_POSITIONING
const REFERENCE_BLACK_WHITE = LibExif.EXIF_TAG_REFERENCE_BLACK_WHITE
const XML_PACKET = LibExif.EXIF_TAG_XML_PACKET
const RELATED_IMAGE_FILE_FORMAT = LibExif.EXIF_TAG_RELATED_IMAGE_FILE_FORMAT
const RELATED_IMAGE_WIDTH = LibExif.EXIF_TAG_RELATED_IMAGE_WIDTH
const RELATED_IMAGE_LENGTH = LibExif.EXIF_TAG_RELATED_IMAGE_LENGTH
const CFA_REPEAT_PATTERN_DIM = LibExif.EXIF_TAG_CFA_REPEAT_PATTERN_DIM
const CFA_PATTERN = LibExif.EXIF_TAG_CFA_PATTERN
const BATTERY_LEVEL = LibExif.EXIF_TAG_BATTERY_LEVEL
const COPYRIGHT = LibExif.EXIF_TAG_COPYRIGHT
const EXPOSURE_TIME = LibExif.EXIF_TAG_EXPOSURE_TIME
const FNUMBER = LibExif.EXIF_TAG_FNUMBER
const IPTC_NAA = LibExif.EXIF_TAG_IPTC_NAA
const IMAGE_RESOURCES = LibExif.EXIF_TAG_IMAGE_RESOURCES
const EXIF_IFD_POINTER = LibExif.EXIF_TAG_EXIF_IFD_POINTER
const INTER_COLOR_PROFILE = LibExif.EXIF_TAG_INTER_COLOR_PROFILE
const EXPOSURE_PROGRAM = LibExif.EXIF_TAG_EXPOSURE_PROGRAM
const SPECTRAL_SENSITIVITY = LibExif.EXIF_TAG_SPECTRAL_SENSITIVITY
const GPS_INFO_IFD_POINTER = LibExif.EXIF_TAG_GPS_INFO_IFD_POINTER
const ISO_SPEED_RATINGS = LibExif.EXIF_TAG_ISO_SPEED_RATINGS
const OECF = LibExif.EXIF_TAG_OECF
const TIME_ZONE_OFFSET = LibExif.EXIF_TAG_TIME_ZONE_OFFSET
const EXIF_VERSION = LibExif.EXIF_TAG_EXIF_VERSION
const DATE_TIME_ORIGINAL = LibExif.EXIF_TAG_DATE_TIME_ORIGINAL
const DATE_TIME_DIGITIZED = LibExif.EXIF_TAG_DATE_TIME_DIGITIZED
const COMPONENTS_CONFIGURATION = LibExif.EXIF_TAG_COMPONENTS_CONFIGURATION
const COMPRESSED_BITS_PER_PIXEL = LibExif.EXIF_TAG_COMPRESSED_BITS_PER_PIXEL
const SHUTTER_SPEED_VALUE = LibExif.EXIF_TAG_SHUTTER_SPEED_VALUE
const APERTURE_VALUE = LibExif.EXIF_TAG_APERTURE_VALUE
const BRIGHTNESS_VALUE = LibExif.EXIF_TAG_BRIGHTNESS_VALUE
const EXPOSURE_BIAS_VALUE = LibExif.EXIF_TAG_EXPOSURE_BIAS_VALUE
const MAX_APERTURE_VALUE = LibExif.EXIF_TAG_MAX_APERTURE_VALUE
const SUBJECT_DISTANCE = LibExif.EXIF_TAG_SUBJECT_DISTANCE
const METERING_MODE = LibExif.EXIF_TAG_METERING_MODE
const LIGHT_SOURCE = LibExif.EXIF_TAG_LIGHT_SOURCE
const FLASH = LibExif.EXIF_TAG_FLASH
const FOCAL_LENGTH = LibExif.EXIF_TAG_FOCAL_LENGTH
const SUBJECT_AREA = LibExif.EXIF_TAG_SUBJECT_AREA
const TIFF_EP_STANDARD_ID = LibExif.EXIF_TAG_TIFF_EP_STANDARD_ID
const MAKER_NOTE = LibExif.EXIF_TAG_MAKER_NOTE
const USER_COMMENT = LibExif.EXIF_TAG_USER_COMMENT
const SUB_SEC_TIME = LibExif.EXIF_TAG_SUB_SEC_TIME
const SUB_SEC_TIME_ORIGINAL = LibExif.EXIF_TAG_SUB_SEC_TIME_ORIGINAL
const SUB_SEC_TIME_DIGITIZED = LibExif.EXIF_TAG_SUB_SEC_TIME_DIGITIZED
const XP_TITLE = LibExif.EXIF_TAG_XP_TITLE
const XP_COMMENT = LibExif.EXIF_TAG_XP_COMMENT
const XP_AUTHOR = LibExif.EXIF_TAG_XP_AUTHOR
const XP_KEYWORDS = LibExif.EXIF_TAG_XP_KEYWORDS
const XP_SUBJECT = LibExif.EXIF_TAG_XP_SUBJECT
const FLASH_PIX_VERSION = LibExif.EXIF_TAG_FLASH_PIX_VERSION
const COLOR_SPACE = LibExif.EXIF_TAG_COLOR_SPACE
const PIXEL_X_DIMENSION = LibExif.EXIF_TAG_PIXEL_X_DIMENSION
const PIXEL_Y_DIMENSION = LibExif.EXIF_TAG_PIXEL_Y_DIMENSION
const RELATED_SOUND_FILE = LibExif.EXIF_TAG_RELATED_SOUND_FILE
const INTEROPERABILITY_IFD_POINTER = LibExif.EXIF_TAG_INTEROPERABILITY_IFD_POINTER
const FLASH_ENERGY = LibExif.EXIF_TAG_FLASH_ENERGY
const SPATIAL_FREQUENCY_RESPONSE = LibExif.EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE
const FOCAL_PLANE_X_RESOLUTION = LibExif.EXIF_TAG_FOCAL_PLANE_X_RESOLUTION
const FOCAL_PLANE_Y_RESOLUTION = LibExif.EXIF_TAG_FOCAL_PLANE_Y_RESOLUTION
const FOCAL_PLANE_RESOLUTION_UNIT = LibExif.EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT
const SUBJECT_LOCATION = LibExif.EXIF_TAG_SUBJECT_LOCATION
const EXPOSURE_INDEX = LibExif.EXIF_TAG_EXPOSURE_INDEX
const SENSING_METHOD = LibExif.EXIF_TAG_SENSING_METHOD
const FILE_SOURCE = LibExif.EXIF_TAG_FILE_SOURCE
const SCENE_TYPE = LibExif.EXIF_TAG_SCENE_TYPE
const NEW_CFA_PATTERN = LibExif.EXIF_TAG_NEW_CFA_PATTERN
const CUSTOM_RENDERED = LibExif.EXIF_TAG_CUSTOM_RENDERED
const EXPOSURE_MODE = LibExif.EXIF_TAG_EXPOSURE_MODE
const WHITE_BALANCE = LibExif.EXIF_TAG_WHITE_BALANCE
const DIGITAL_ZOOM_RATIO = LibExif.EXIF_TAG_DIGITAL_ZOOM_RATIO
const FOCAL_LENGTH_IN_35MM_FILM = LibExif.EXIF_TAG_FOCAL_LENGTH_IN_35MM_FILM
const SCENE_CAPTURE_TYPE = LibExif.EXIF_TAG_SCENE_CAPTURE_TYPE
const GAIN_CONTROL = LibExif.EXIF_TAG_GAIN_CONTROL
const CONTRAST = LibExif.EXIF_TAG_CONTRAST
const SATURATION = LibExif.EXIF_TAG_SATURATION
const SHARPNESS = LibExif.EXIF_TAG_SHARPNESS
const DEVICE_SETTING_DESCRIPTION = LibExif.EXIF_TAG_DEVICE_SETTING_DESCRIPTION
const SUBJECT_DISTANCE_RANGE = LibExif.EXIF_TAG_SUBJECT_DISTANCE_RANGE
const IMAGE_UNIQUE_ID = LibExif.EXIF_TAG_IMAGE_UNIQUE_ID
const GAMMA = LibExif.EXIF_TAG_GAMMA
const PRINT_IMAGE_MATCHING = LibExif.EXIF_TAG_PRINT_IMAGE_MATCHING
const PADDING = LibExif.EXIF_TAG_PADDING
